#!/bin/lua
fs.delete("/turtle/")

-- constants
local src = "https://raw.github.com/IanWernecke/ccturtle/master/"
local dst = "/turtle/"

-- simple function to write data to files
local function download(data, file)
   local f = fs.open(file, "w")
   f.write(data)
   f.close()
end

local directories = {
  "/turtle/.",
  "/turtle/apis",
  "/turtle/bore",
  "/turtle/build",
  "/turtle/build/signal",
  "/turtle/clear",
  "/turtle/clear/forward",
  "/turtle/clear/magnet",
  "/turtle/clear/magnet/spiral",
  "/turtle/clear/spiral",
  "/turtle/describe",
  "/turtle/dig",
  "/turtle/fill",
  "/turtle/fill/spiral",
  "/turtle/inventory",
  "/turtle/mine",
  "/turtle/mine/shelf",
  "/turtle/mine/stairs",
  "/turtle/mine/vein",
  "/turtle/move",
  "/turtle/place",
  "/turtle/punch",
  "/turtle/seek",
  "/turtle/slide",
  "/turtle/strafe",
  "/turtle/util"
}

local files = {}
files[src.."basic"] = dst.."basic"
files[src.."sanitize"] = dst.."sanitize"
files[src.."setup"] = dst.."setup"
files[src.."startup"] = dst.."startup"
files[src.."update"] = dst.."update"
files[src.."apis/basic"] = dst.."apis/basic"
files[src.."apis/bore"] = dst.."apis/bore"
files[src.."apis/clear"] = dst.."apis/clear"
files[src.."apis/cleft"] = dst.."apis/cleft"
files[src.."apis/con"] = dst.."apis/con"
files[src.."apis/describe"] = dst.."apis/describe"
files[src.."apis/detect"] = dst.."apis/detect"
files[src.."apis/dig"] = dst.."apis/dig"
files[src.."apis/fill"] = dst.."apis/fill"
files[src.."apis/inventory"] = dst.."apis/inventory"
files[src.."apis/match"] = dst.."apis/match"
files[src.."apis/mine"] = dst.."apis/mine"
files[src.."apis/move"] = dst.."apis/move"
files[src.."apis/place"] = dst.."apis/place"
files[src.."apis/punch"] = dst.."apis/punch"
files[src.."apis/replace"] = dst.."apis/replace"
files[src.."apis/seek"] = dst.."apis/seek"
files[src.."apis/slide"] = dst.."apis/slide"
files[src.."bore/back"] = dst.."bore/back"
files[src.."bore/down"] = dst.."bore/down"
files[src.."bore/forward"] = dst.."bore/forward"
files[src.."bore/left"] = dst.."bore/left"
files[src.."bore/right"] = dst.."bore/right"
files[src.."bore/up"] = dst.."bore/up"
files[src.."build/catwalk"] = dst.."build/catwalk"
files[src.."build/wall"] = dst.."build/wall"
files[src.."build/signal/home"] = dst.."build/signal/home"
files[src.."clear/tunnel"] = dst.."clear/tunnel"
files[src.."clear/forward/both"] = dst.."clear/forward/both"
files[src.."clear/forward/left"] = dst.."clear/forward/left"
files[src.."clear/forward/right"] = dst.."clear/forward/right"
files[src.."clear/magnet/spiral/left"] = dst.."clear/magnet/spiral/left"
files[src.."clear/magnet/spiral/right"] = dst.."clear/magnet/spiral/right"
files[src.."clear/spiral/left"] = dst.."clear/spiral/left"
files[src.."clear/spiral/right"] = dst.."clear/spiral/right"
files[src.."describe/back"] = dst.."describe/back"
files[src.."describe/down"] = dst.."describe/down"
files[src.."describe/forward"] = dst.."describe/forward"
files[src.."describe/left"] = dst.."describe/left"
files[src.."describe/right"] = dst.."describe/right"
files[src.."describe/up"] = dst.."describe/up"
files[src.."dig/back"] = dst.."dig/back"
files[src.."dig/down"] = dst.."dig/down"
files[src.."dig/forward"] = dst.."dig/forward"
files[src.."dig/left"] = dst.."dig/left"
files[src.."dig/right"] = dst.."dig/right"
files[src.."dig/up"] = dst.."dig/up"
files[src.."fill/auto"] = dst.."fill/auto"
files[src.."fill/back"] = dst.."fill/back"
files[src.."fill/down"] = dst.."fill/down"
files[src.."fill/forward"] = dst.."fill/forward"
files[src.."fill/gap"] = dst.."fill/gap"
files[src.."fill/layer"] = dst.."fill/layer"
files[src.."fill/left"] = dst.."fill/left"
files[src.."fill/right"] = dst.."fill/right"
files[src.."fill/up"] = dst.."fill/up"
files[src.."fill/spiral/left"] = dst.."fill/spiral/left"
files[src.."fill/spiral/right"] = dst.."fill/spiral/right"
files[src.."inventory/count"] = dst.."inventory/count"
files[src.."inventory/select"] = dst.."inventory/select"
files[src.."mine/skylight"] = dst.."mine/skylight"
files[src.."mine/skystone"] = dst.."mine/skystone"
files[src.."mine/trench"] = dst.."mine/trench"
files[src.."mine/trenchSeek"] = dst.."mine/trenchSeek"
files[src.."mine/shelf/left"] = dst.."mine/shelf/left"
files[src.."mine/shelf/right"] = dst.."mine/shelf/right"
files[src.."mine/stairs/down"] = dst.."mine/stairs/down"
files[src.."mine/vein/back"] = dst.."mine/vein/back"
files[src.."mine/vein/down"] = dst.."mine/vein/down"
files[src.."mine/vein/forward"] = dst.."mine/vein/forward"
files[src.."mine/vein/left"] = dst.."mine/vein/left"
files[src.."mine/vein/right"] = dst.."mine/vein/right"
files[src.."mine/vein/up"] = dst.."mine/vein/up"
files[src.."move/back"] = dst.."move/back"
files[src.."move/climb"] = dst.."move/climb"
files[src.."move/down"] = dst.."move/down"
files[src.."move/forward"] = dst.."move/forward"
files[src.."move/left"] = dst.."move/left"
files[src.."move/magnet"] = dst.."move/magnet"
files[src.."move/right"] = dst.."move/right"
files[src.."move/up"] = dst.."move/up"
files[src.."place/back"] = dst.."place/back"
files[src.."place/down"] = dst.."place/down"
files[src.."place/forward"] = dst.."place/forward"
files[src.."place/left"] = dst.."place/left"
files[src.."place/right"] = dst.."place/right"
files[src.."place/up"] = dst.."place/up"
files[src.."punch/back"] = dst.."punch/back"
files[src.."punch/down"] = dst.."punch/down"
files[src.."punch/forward"] = dst.."punch/forward"
files[src.."punch/left"] = dst.."punch/left"
files[src.."punch/right"] = dst.."punch/right"
files[src.."punch/up"] = dst.."punch/up"
files[src.."seek/back"] = dst.."seek/back"
files[src.."seek/down"] = dst.."seek/down"
files[src.."seek/forward"] = dst.."seek/forward"
files[src.."seek/left"] = dst.."seek/left"
files[src.."seek/right"] = dst.."seek/right"
files[src.."seek/up"] = dst.."seek/up"
files[src.."slide/back"] = dst.."slide/back"
files[src.."slide/down"] = dst.."slide/down"
files[src.."slide/forward"] = dst.."slide/forward"
files[src.."slide/left"] = dst.."slide/left"
files[src.."slide/right"] = dst.."slide/right"
files[src.."slide/up"] = dst.."slide/up"
files[src.."strafe/left"] = dst.."strafe/left"
files[src.."strafe/right"] = dst.."strafe/right"
files[src.."util/detail"] = dst.."util/detail"
files[src.."util/select"] = dst.."util/select"
files[src.."util/stub"] = dst.."util/stub"

-- make each of the required directories
for i=1,#directories do
   fs.makeDir(directories[i])
end

-- request each of the files to be retrieved
for i=1,#files do
   http.request(src..files[i])
end

-- asynchronously download all of the files
local downloaded = 0
local failed = {}
while downloaded < 115 do
   local event, url, handle = os.pullEvent()
   if event == "http_success" then
       download(handle.readAll(),files[url])
       downloaded = downloaded + 1
   elseif event == "http_failure" then
       failed[os.startTime(3)] = url
   elseif event == "timer" and failed[url] then
       print("fail: "..url)
       http.request(failed[url])
   end
end
