#!/bin/lua


function print_system_status()
    -- print the current system label, version, fuel level, and time

    local label = os.getComputerLabel()
    if label == nil then
        label = ""
    end

    print("Label: " .. label)
    print("Version: " .. os.version())
    if turtle then
        current = turtle.getFuelLevel()
        maximum = turtle.getFuelLimit()
        print("Fuel: " .. (current / maximum * 100) .. "%  (" .. current .. " / " .. maximum .. ")")
    end
    print("Time: " .. os.day() .. 'T' .. os.time())

end


function load_turtle_apis()
    -- load apis to be used by a turtle

    -- simple api loads
    -- requires: nil
    os.loadAPI("/apis/bore")
    os.loadAPI("/apis/clear")
    os.loadAPI("/apis/con")
    os.loadAPI("/apis/describe")
    os.loadAPI("/apis/detect")
    os.loadAPI("/apis/dig")
    os.loadAPI("/apis/inventory")
    os.loadAPI("/apis/match")
    os.loadAPI("/apis/move")
    os.loadAPI("/apis/ore")
    os.loadAPI("/apis/seek")
    os.loadAPI("/apis/slide")

    -- requires: inventory
    os.loadAPI("/apis/place")

    -- requires: dig, move, place
    os.loadAPI("/apis/builder")

    -- requires: bore, move
    os.loadAPI("/apis/punch")

    -- requires: detect, dig, punch
    os.loadAPI("/apis/cleft")

    -- requires: place, seek
    os.loadAPI("/apis/fill")

    -- requires: match, dig
    os.loadAPI("/apis/mine")

    -- requires: seek, match, dig, place, move
    os.loadAPI("/apis/replace")

end


function main()
    -- print the system status and load any required apis

    print_system_status()
    if turtle then
        load_turtle_apis()
    end

end
main()
