#!/usr/bin/lua


function build_row(row)

  for column=1,#row do

    -- set the block below
    local char = row:sub(column,column)
    if char == '#' then
      if not turtle.detectDown() then
        place.down()
      end
    elseif char == '.' then
      clear.down()
    end

    -- dig forward
    if column ~= #row then dig.forward() end
  end
  move.back(#row - 1)

end


function build_grid(grid)
  -- for each row in the grid
  for i=1,#grid do

    -- orient to one side, build the row
    turtle.turnLeft()
    build_row(grid[i])
    turtle.turnRight()

    -- if less than max, dig forward
    if i ~= #grid then dig.forward() end

  end
  move.back(#grid - 1)
end


local x = {
  "#.#",
  ".#."
}
build_grid(x)
