#!/bin/lua

-- remove old setup script
shell.run("rm /setup")

-- download the setup script
shell.run("wget https://raw.github.com/IanWernecke/ccturtle/master/setup setup")

-- call the setup script
shell.run("/setup")
