#!/bin/lua

-- remove old setup script
shell.run("rm /setup")

-- download the setup script
local data = http.get("https://raw.github.com/IanWernecke/ccturtle/master/setup").readAll()

-- write the setup script
local f = fs.open("/setup", "w")
f.write(data)
f.close()

-- call the setup script
shell.run("/setup")

