#!/bin/lua

-- inventory/select program

local args = {...}

-- Check number of arguments for usage
if #args ~= 1 then
    error( "Argument required for length of run." )
end

inventory.select(args[1])
