#!/bin/lua

local ins = turtle.inspect

turtle.turnLeft()
turtle.turnLeft()

local data = ins()
local count = mine.vein(data.name)

turtle.turnLeft()
turtle.turnLeft()

print("Mined " .. tostring(count) .. " " .. data.name)

