#!/bin/lua


-- fill/spiralRight program
-- fill in a rectangular hole by spiralling backwards

canRow = true
while canRow do

	canRow = false

	-- fill the entire row
	while turtle.back() do
		canRow = true
                if not place.forward() then
                    print('Out of blocks! Exiting ...')
                    return false
                end
	end

	turtle.turnRight()

end

turtle.up()
place.down()

