#!/bin/lua

-- mine/stairs/down program

-- collect the arguments from the command line
local args = {...}


-- Check number of arguments for usage
if #args ~= 1 then
    error( "Argument required for depth of staircase." )
end


-- number of levels down we wish to go down
local MAX = tonumber(args[1])
local depth = 0
while depth < MAX do

    dig.forward(6)

    -- move back five (off by one so we don't make a wall)
    move.back(5)

    -- move down one
    if turtle.detectDown() and depth < MAX -1 then
        dig.down()
    end

    depth = depth + 1

end
