#!/bin/lua

local apiLogic = function(detect, dig, move, num)
    local i = 0
    while i < num do
        if detect() then
            dig()
        end
        if move() then
            i = i + 1
        else
            return i
        end
    end
    return i
end

function back(num)
    turtle.turnLeft()
    turtle.turnLeft()
    return apiLogic(turtle.dig, num)
end
function down(num)
   return apiLogic(turtle.digDown, num) 
end
function forward(num)
    return apiLogic(turtle.dig, num)
end
function left(num)
    turtle.turnLeft()
    return apiLogic(turtle.dig, num)
end
function right(num)
    turtle.turnRight()
    return apiLogic(turtle.dig, num)
end
function up(num)
    return apiLogic(turtle.digUp, num)
end

