#!/bin/lua


-- program apis/bore
-- logic and controlling for seek segment
local boreLogic = function( detect, action, movement )
    local i = 0
    while detect() do
        action()
        movement()
        i = i + 1
    end
    return i
end

function back()
    turtle.turnLeft()
    turtle.turnLeft()
    return forward()
end
function forward()
    return boreLogic(turtle.detect, turtle.dig, turtle.forward)
end
function down()
    return boreLogic(turtle.detectDown, turtle.digDown, turtle.down)
end
function left()
    turtle.turnLeft()
    return forward()
end
function right()
    turtle.turnRight()
    return forward()
end
function up()
    return boreLogic(turtle.detectUp, turtle.digUp, turtle.up)
end

