#!/bin/lua

ANDESITE = "chisel:andesite"
COAL_ORE = "minecraft:coal_ore"
COBBLESTONE = "minecraft:cobblestone"
DIRT = "minecraft:dirt"
GRASS = "minecraft:grass"
MARBLE = "chisel:marble"
NETHER_GOLD = "NetherOres:tile.netherores.ore.0"
PLANKS = "minecraft:planks"
SKYSTONE = "appliedenergistics2:tile.BlockSkyStone"
STONE = "minecraft:stone"
STONEBRICK = "minecraft:stonebrick"
