#!/bin/lua


-- api core logic
local dig_logic = function(detect, dig, move, num)

    -- optional arg fix
    if num == nil then
        num = 1
    end

    for i=1,num do

        if detect() then
            dig()
        end

        if not move() then
            return i
        end

    end
    return num

end


-- six basic directions
function back(num)
    turtle.turnLeft()
    turtle.turnLeft()
    return forward(num)
end
function down(num)
    return dig_logic(turtle.detectDown, turtle.digDown, turtle.down, num) 
end
function forward(num)
    return dig_logic(turtle.detect, turtle.dig, turtle.forward, num)
end
function left(num)
    turtle.turnLeft()
    return forward(num)
end
function right(num)
    turtle.turnRight()
    return forward(num)
end
function up(num)
    return dig_logic(turtle.detectUp, turtle.digUp, turtle.up, num) 
end

