#!/bin/lua

local digLogic = function(detect, dig, move, num)

    -- optional arg fix
    if num == nil then
        num = 1
    end

    local i = 0
    while i < num do

        if detect() then
            dig()
        end

        if move() then
            i = i + 1
        else
            return i
        end

    end
    return i

end

function back(num)
    turtle.turnLeft()
    turtle.turnLeft()
    return forward(num)
end
function down(num)
    return digLogic(turtle.detectDown, turtle.digDown, turtle.down, num) 
end
function forward(num)
    return digLogic(turtle.detect, turtle.dig, turtle.forward, num)
end
function left(num)
    turtle.turnLeft()
    return forward(num)
end
function right(num)
    turtle.turnRight()
    return forward(num)
end
function up(num)
    return digLogic(turtle.detectUp, turtle.digUp, turtle.up, num) 
end

