#!/bin/lua


-- api core logic
-- methods for filling areas (simple)
local fill_logic = function(seeker, mover, placer)
    local moved = seeker()
    for i=1,moved do
        mover()
        placer()
    end
    return moved
end


-- six basic directions
function back()
    turtle.turnLeft()
    turtle.turnLeft()
    return forward()
end 
function down()
    return fill_logic(seek.down, turtle.up, place.down)
end
function forward()
    return fill_logic(seek.forward, turtle.back, place.forward)
end
function left()
    turtle.turnLeft()
    return forward()
end
function right()
    turtle.turnRight()
    return forward()
end
function up()
    return fill_logic(seek.up, turtle.down, place.up)
end

