#!/bin/lua


-- program apis/place_logic
-- logic to place_logic the next available block
local place_logic = function(place_string, action_command)

    -- select the specific place string if it is not already selected
    if inventory.current() ~= place_string then
        assert(inventory.contains(place_string), "Inventory does not contain: "..place_string)
        inventory.select(place_string)
    end

    -- if able to place_logic block, success!
    if action_command() then
        return true
    end

    turtle.select(inventory.first())
    return action_command()

end


-- series of commands to always place_logic any available blocks (after current spot)
function back(place_string)
    turtle.turnLeft()
    turtle.turnleft()
    return forward(place_string)
end
function forward(place_string)
    return place_logic(place_string, turtle.place)
end
function down(place_string)
    return place_logic(place_string, turtle.placeDown)
end
function left(place_string)
    turtle.turnLeft()
    return forward(place_string)
end
function right(place_string)
    turtle.turnRight()
    return forward(place_string)
end
function up(place_string)
    return place_logic(place_string, turtle.placeUp)
end

