#!/bin/lua


-- program apis/place_logic
-- logic to place_logic the next available block
local place_logic = function(action_command)

    -- if able to place_logic block, success!
    if action_command() then
        return true
    end

    turtle.select(inventory.first())
    return action_command()

end


-- series of commands to always place_logic any available blocks (after current spot)
function back()
    turtle.turnLeft()
    turtle.turnleft()
    return forward()
end
function forward()
    return place_logic(turtle.place)
end
function down()
    return place_logic(turtle.placeDown)
end
function left()
    turtle.turnLeft()
    return forward()
end
function right()
    turtle.turnRight()
    return forward()
end
function up()
    return place_logic(turtle.placeUp)
end

