#!/bin/lua


-- file: apis/punch
-- set of functions for boring and returning
-- these functions do not follow the normal schema
-- because they revert their turns to their original
-- orientation
function back()
    local i = 0
    turtle.turnLeft()
    turtle.turnLeft()
    i = forward()
    turtle.turnLeft()
    turtle.turnLeft()
    return i
end
function down()
    return move.up(bore.down())
end
function forward()
    return move.back(bore.forward())
end
function left()
    local i = 0
    turtle.turnLeft()
    i = forward()
    turtle.turnRight()
    return i
end
function right()
    local i = 0
    turtle.turnRight()
    i = forward()
    turtle.turnLeft()
    return i
end
function up()
    return move.down(bore.up())
end

