#!/bin/lua

-- requires: dig, mine, turn

-- print the usage and exit
local usage = function()
  print("Usage: [SHAFTS=5]")
  error()
end


-- collect the arguments from the command line
local args = {...}

-- check the number of arguments
if #args > 1 then
  usage()
end


-- set the global values
SHAFTS = (#args > 0 and tonumber(args[1]) or 5)


function find_next_shaft_position(x, y)

  local new_x, new_y = x, y
  new_x = new_x + 1
  while (new_x + (new_y * 2)) % 5 ~= 0 then
    new_y = new_y + 1
  end
  return new_x, new_y

end


local shaft_count, x, y = 0, 0, 0
while shaft_count < SHAFTS do

  -- move forward and right the x amounts
  dig.forward(x)
  dig.right(y)

  -- if the shaft has already been dug, find next
  while match.down(con.COBBLESTONE) do
    local next_x, next_y = find_next_shaft_position(x, y)
    dig.back(y)
    dig.right(next_x - x)
    dig.right(next_y)
    x, y = next_x, next_y
  end

  -- mine the ore shaft and record it
  mine.ore_shaft()
  shaft_count = shaft_count + 1

  -- place a cobblestone down if possible
  if inventory.contains(con.COBBLESTONE) then
    place.down(con.COBBLESTONE)
  end

  -- return to the starting position to dump goods
  dig.back(y)
  dig.left(x)

  -- dump goods and prepare to begin again
  inventory.drop()
  turn.back()

  -- find the next coordinates in case there are more shafts to be dug
  x, y = find_next_shaft_position(x, y)

end
